AcunMedyaFurniter/Areas/Admin/Controllers/SocialMediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AcunMedyaFurniter.DAL.Context;
using AcunMedyaFurniter.DAL.Entities;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AcunMedyaFurniter.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class SocialMediaController : Controller
    {
        private readonly FurnitureContext _context;

        public SocialMediaController(FurnitureContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var values = _context.SocialMedias.ToList();
            return View(values);
        }

        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia socialMedia)
        {
            if (ModelState.IsValid)
            {
                _context.SocialMedias.Add(socialMedia);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index");
        }

        public IActionResult EditSocialMedia(int id)
        {
            var socialMedia = _context.SocialMedias.Find(id);
            if (socialMedia == null)
            {
                return NotFound();
            }
            return View(socialMedia);
        }

        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia socialMedia)
        {
            if (ModelState.IsValid)
            {
                _context.SocialMedias.Update(socialMedia);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(socialMedia);
        }

        [HttpPost]
        public IActionResult DeleteSocialMedia(int id)
        {
            var socialMedia = _context.SocialMedias.Find(id);
            if (socialMedia != null)
            {
                _context.SocialMedias.Remove(socialMedia);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

AcunMedyaFurniter/Areas/Admin/Views/SocialMedia/AddSocialMedia.cshtml
@model AcunMedyaFurniter.DAL.Entities.SocialMedia

@{

    Layout = "~/Views/AdminLayout/Index.cshtml"; // Layout dosyasının yolunu kontrol edin
}


<div class="card">
    <div class="card-header">
        <div class="card-title">Ürün Ekleme Sayfası</div>
    </div>
    <div class="card-body">


        <form asp-action="CreateSocialMedia" method="post">
            <div class="form-group">
                <label asp-for="Icon" class="font-weight-bold"></label>
                <input asp-for="Icon" class="form-control" placeholder="İkon " />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="font-weight-bold"></label>
                <input asp-for="Name" type="number" class="form-control" placeholder="Ad" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Url" class="font-weight-bold"></label>
                <textarea asp-for="Url" class="form-control" placeholder="Url" rows="4"></textarea>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>

           

            <button type="submit" class="btn btn-primary">Kaydet</button>
            <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
        </form>
    </div>

AcunMedyaFurniter/Areas/Admin/Views/SocialMedia/EditSocialMedia.cshtml
@model AcunMedyaFurniter.DAL.Entities.SocialMedia

@{

    Layout = "~/Views/AdminLayout/Index.cshtml"; // Layout dosyasının yolunu kontrol edin
}


<div class="card">
    <div class="card-header">
        <div class="card-title">Ürün Ekleme Sayfası</div>
    </div>
    <div class="card-body">


        <form asp-action="CreateSocialMedia" method="post">
            <div class="form-group">
                <label asp-for="Icon" class="font-weight-bold"></label>
                <input asp-for="Icon" class="form-control" placeholder="İkon " />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="font-weight-bold"></label>
                <input asp-for="Name" type="number" class="form-control" placeholder="Ad" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Url" class="font-weight-bold"></label>
                <textarea asp-for="Url" class="form-control" placeholder="Url" rows="4"></textarea>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>



            <button type="submit" class="btn btn-primary">Kaydet</button>
            <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
        </form>
    </div>

AcunMedyaFurniter/Areas/Admin/Views/SocialMedia/Index.cshtml
@model List<AcunMedyaFurniter.DAL.Entities.SocialMedia>

@{
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Sosyal Medya Hesaplarımız</h4>
                <form method="get" action="@Url.Action("CreateSocialMedia", "SocialMedia")" class="ms-auto">
                    <button type="submit" class="btn btn-primary btn-round">
                        <i class="fa fa-plus"></i> Ekle
                    </button>
                </form>
            </div>
        </div>
        <div class="card-body">
            <!-- Add Modal -->
            <div class="modal fade" id="addRowModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-0">
                            <h5 class="modal-title">
                                <span class="fw-mediumbold"> Yeni</span>
                                <span class="fw-light"> Abone </span>
                            </h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="small">Yeni bir abone oluşturmak için bu formu kullanın, tüm alanları doldurduğunuzdan emin olun.</p>
                            <form asp-action="AddSocialMedia" asp-controller="SocialMedia" method="post">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group form-group-default">
                                            <label>Icon</label>
                                            <select id="addIcon" name="Icon" class="form-control" required>
                                                <option value="fa fa-facebook">Facebook</option>
                                                <option value="fa fa-twitter">Twitter</option>
                                                <option value="fa fa-instagram">Instagram</option>
                                                <option value="fa fa-linkedin">LinkedIn</option>
                                                <option value="fa fa-youtube">YouTube</option>
                                                <option value="fa fa-pinterest">Pinterest</option>
                                                <option value="fa fa-snapchat">Snapchat</option>
                                                <option value="fa fa-tiktok">TikTok</option>
                                                <option value="fa fa-whatsapp">WhatsApp</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pe-0">
                                        <div class="form-group form-group-default">
                                            <label>Ad</label>
                                            <input id="addName" name="Name" type="text" class="form-control" required />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Url</label>
                                            <input id="addUrl" name="Url" type="text" class="form-control" required />
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer border-0">
                                    <button type="submit" class="btn btn-primary">Ekle</button>
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Kapat</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Edit Modal -->
            <div class="modal fade" id="editRowModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-0">
                            <h5 class="modal-title">
                                <span class="fw-mediumbold"> Güncelle</span>
                                <span class="fw-light"> Abone </span>
                            </h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="small">Abone bilgilerini güncellemek için bu formu kullanın, tüm alanları doldurduğunuzdan emin olun.</p>
                            <form asp-action="EditSocialMedia" asp-controller="SocialMedia" method="post">
                                <input type="hidden" id="editId" name="SocialMediaID" />
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group form-group-default">
                                            <label>Icon</label>
                                            <select id="editIcon" name="Icon" class="form-control" required>
                                                <option value="fa fa-facebook">Facebook</option>
                                                <option value="fa fa-twitter">Twitter</option>
                                                <option value="fa fa-instagram">Instagram</option>
                                                <option value="fa fa-linkedin">LinkedIn</option>
                                                <option value="fa fa-youtube">YouTube</option>
                                                <option value="fa fa-pinterest">Pinterest</option>
                                                <option value="fa fa-snapchat">Snapchat</option>
                                                <option value="fa fa-tiktok">TikTok</option>
                                                <option value="fa fa-whatsapp">WhatsApp</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pe-0">
                                        <div class="form-group form-group-default">
                                            <label>Ad</label>
                                            <input id="editName" name="Name" type="text" class="form-control" required />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Url</label>
                                            <input id="editUrl" name="Url" type="text" class="form-control" required />
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer border-0">
                                    <button type="submit" class="btn btn-primary">Güncelle</button>
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Kapat</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="add-row" class="display table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Ikon</th>
                            <th>İsim</th>
                            <th>Url</th>
                            <th style="width: 15%">İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var subscriber in Model)
                        {
                            <tr>
                                <td><i class="@subscriber.Icon"></i></td>
                                <td>@subscriber.Name</td>
                                <td><a href="@subscriber.Url" target="_blank">@subscriber.Url</a></td>
                                <td>
                                    <div class="form-button-action">
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#editRowModal" class="btn btn-link btn-primary btn-lg" onclick="editSubscriber('@subscriber.SocialMediaID', '@subscriber.Icon', '@subscriber.Name', '@subscriber.Url')">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                        <form asp-action="DeleteSocialMedia" asp-controller="SocialMedia" method="post" style="display:inline;">
                                            @Html.AntiForgeryToken()
                                            <input type="hidden" name="id" value="@subscriber.SocialMediaID" />
                                            <button type="submit" data-bs-toggle="tooltip" title="Remove" class="btn btn-link btn-danger">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>document.querySelectorAll('form').forEach(form => {
        form.addEventListener('submit', event => {
            if (!confirm('Bu öğeyi silmek istediğinizden emin misiniz?')) {
                event.preventDefault();
            }
        });
    });

    function editSubscriber(id, icon, name, url) {
        document.getElementById('editId').value = id;
        document.getElementById('editIcon').value = icon;
        document.getElementById('editName').value = name;
        document.getElementById('editUrl').value = url;
    }</script>