AcunMedyaFurniter/Areas/Admin/Controllers/SubscriberController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using AcunMedyaFurniter.DAL.Context;
using AcunMedyaFurniter.DAL.Entities;

namespace AcunMedyaFurniter.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class SubscriberController : Controller
    {

        private readonly FurnitureContext _context;

        public SubscriberController(FurnitureContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var values = _context.Subscribers.ToList();
            return View(values);
        }

        [HttpPost]
        public IActionResult AddSubscriber(Subscriber subscriber)
        {
            if (ModelState.IsValid)
            {
                _context.Subscribers.Add(subscriber);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index", _context.Subscribers.ToList());
        }

        [HttpPost]
        public IActionResult DeleteSubscriber(int id)
        {
            var subscriber = _context.Subscribers.Find(id);
            if (subscriber != null)
            {
                _context.Subscribers.Remove(subscriber);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

AcunMedyaFurniter/Areas/Admin/Views/Subscriber/Index.cshtml
@model List<AcunMedyaFurniter.DAL.Entities.Subscriber>

@{
    Layout = "~/Views/AdminLayout/Index.cshtml";
}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Abone Olan Kullanıcılar</h4>
                
            </div>
        </div>
        <div class="card-body">
            <!-- Modal -->
            <div class="modal fade" id="addRowModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-0">
                            <h5 class="modal-title">
                                <span class="fw-mediumbold"> New</span>
                                <span class="fw-light"> Subscriber </span>
                            </h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="small">Create a new subscriber using this form, make sure you fill them all.</p>
                            <form asp-action="AddSubscriber" asp-controller="Subscriber" method="post">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group form-group-default">
                                            <label>Name</label>
                                            <input id="addName" name="Name" type="text" class="form-control" placeholder="fill name" required />
                                        </div>
                                    </div>
                                    <div class="col-md-6 pe-0">
                                        <div class="form-group form-group-default">
                                            <label>Position</label>
                                            <input id="addPosition" name="Position" type="text" class="form-control" placeholder="fill position" required />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Office</label>
                                            <input id="addOffice" name="Office" type="text" class="form-control" placeholder="fill office" required />
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer border-0">
                                    <button type="submit" class="btn btn-primary">Add</button>
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="add-row" class="display table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th style="width: 10%">İşlemler</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var subscriber in Model)
                        {
                            <tr>
                                <td>@subscriber.Name</td>
                                <td>@subscriber.Email</td>
                                <td>
                                    <div class="form-button-action">
                                        <form asp-action="DeleteSubscriber" asp-controller="Subscriber" method="post" style="display:inline;">
                                            @Html.AntiForgeryToken()
                                            <input type="hidden" name="id" value="@subscriber.SubscriberID" />
                                            <button type="submit" data-bs-toggle="tooltip" title="Remove" class="btn btn-link btn-danger">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>document.querySelectorAll('form').forEach(form => {
        form.addEventListener('submit', event => {
            if (!confirm('Are you sure you want to delete this item?')) {
                event.preventDefault();
            }
        });
    });</script>