AcunMedyaFurniter/Areas/Admin/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AcunMedyaFurniter.DAL.Context;
using AcunMedyaFurniter.DAL.Entities;
using Microsoft.AspNetCore.Mvc;

namespace AcunMedyaFurniter.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class TeamController : Controller
    {
        private readonly FurnitureContext _context;

        public TeamController(FurnitureContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var teams = _context.Teams.ToList();
            return View(teams);
        }

        [HttpGet]
        public IActionResult CreateTeam()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTeam(Team team)
        {
            if (ModelState.IsValid)
            {
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateTeam(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTeam(Team team)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Teams.Update(team);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Lütfen Tekrar Deneyiniz.");
                }
            }
            return View(team);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTeam(int id)
        {
            var team = await _context.Teams.FindAsync(id);

            if (team == null)
            {
                return NotFound();
            }

            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

AcunMedyaFurniter/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AcunMedyaFurniter.DAL.Context;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AcunMedyaFurniter.Controllers
{
    public class ProductController : Controller
    {
        private readonly FurnitureContext _context;

        public ProductController(FurnitureContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var values = _context.Products.ToList();
            return View(values);
        }
    }
}

AcunMedyaFurniter/Areas/Admin/Views/Team/CreateTeam.cshtml
@model AcunMedyaFurniter.DAL.Entities.Team

@{
   
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="card">
    <div class="card-header">
        <div class="card-title">Yeni Ekip Üyesi Ekleme Sayfası</div>
    </div>
    <div class="card-body">
        <form asp-action="CreateTeam" method="post">
            <div class="form-group">
                <label asp-for="NameSurname" class="font-weight-bold">Ad ve Soyad</label>
                <input asp-for="NameSurname" class="form-control" placeholder="Ad ve Soyad" />
                <span asp-validation-for="NameSurname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Title" class="font-weight-bold">Başlık</label>
                <input asp-for="Title" class="form-control" placeholder="Başlık" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="font-weight-bold">Açıklama</label>
                <textarea asp-for="Description" class="form-control" placeholder="Açıklama" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUrl" class="font-weight-bold">Görsel URL'si</label>
                <input asp-for="ImageUrl" type="text" class="form-control" placeholder="Görsel URL'si" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Kaydet</button>
            <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
        </form>
    </div>
</div>

AcunMedyaFurniter/Areas/Admin/Views/Team/Index.cshtml
@model List<AcunMedyaFurniter.DAL.Entities.Team>

@{

    Layout = "~/Views/AdminLayout/Index.cshtml"; // Layout dosyasının yolunu kontrol edin
}

<div class="card">
    <div class="card-header">
        <div class="card-title">Ekibimiz </div>
    </div>
    <div class="card-body">
        
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ad Soyad </th>
                    <th scope="col">Başlık</th>
                    <th scope="col">Açıklama</th>
                    <th scope="col">Resim</th>
                    <th scope="col">İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Count > 0)
                {
                    int count = 0;
                    foreach (var item in Model)
                    {
                        count++;
                        <tr>
                            <td>@count</td>

                            <td>@item.NameSurname</td>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td><img src="@item.ImageUrl" style="width:50px;height:50px" /></td>
                            <td>
                                <form method="post" action="@Url.Action("DeleteTeam", new { id = item.TeamId })" style="display:inline;">
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="btn btn-outline-danger" onclick="return confirm('Bu ürünü silmek istediğinizden emin misiniz?')">Sil</button>
                                </form>

                                <a asp-action="UpdateProduct" asp-controller="Product" asp-route-id="@item.TeamId" class="btn btn-outline-success">Güncelle</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6" class="text-center">No products found.</td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-action="CreateTeam" asp-controller="Team" class="btn btn-outline-warning">Ekip Üyesi Ekle</a>
    </div>
</div>

AcunMedyaFurniter/Areas/Admin/Views/Team/UpdateTeam.cshtml
@model AcunMedyaFurniter.DAL.Entities.Team

@{

   
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="card">
    <div class="card-header">
        <div class="card-title">Ekip Üyesini Güncelleme Sayfası</div>
    </div>
    <div class="card-body">
        <form asp-action="UpdateTeam" method="post">
            <input type="hidden" asp-for="TeamId" />

            <div class="form-group">
                <label asp-for="NameSurname" class="font-weight-bold">Ad ve Soyad</label>
                <input asp-for="NameSurname" class="form-control" placeholder="Ad ve Soyad" />
                <span asp-validation-for="NameSurname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Title" class="font-weight-bold">Başlık</label>
                <input asp-for="Title" class="form-control" placeholder="Başlık" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="font-weight-bold">Açıklama</label>
                <textarea asp-for="Description" class="form-control" placeholder="Açıklama" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUrl" class="font-weight-bold">Görsel URL'si</label>
                <input asp-for="ImageUrl" type="text" class="form-control" placeholder="Görsel URL'si" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Güncelle</button>
            <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
        </form>
    </div>
</div>